/**
 * Builds the next meeting's agenda from unresolved items and action items.
 * Called as part of the post-meeting pipeline.
 */
async function buildNextAgenda({ actionItems, unresolvedItems, nextMeetingAgenda }) {
  // The agenda is already generated by Claude in the post-meeting output.
  // This module formats it for storage and display.
  const agenda = []

  // Add AI-generated agenda items
  if (nextMeetingAgenda && nextMeetingAgenda.length > 0) {
    agenda.push(...nextMeetingAgenda)
  }

  // Add any unresolved items as agenda items
  if (unresolvedItems && unresolvedItems.length > 0) {
    for (const item of unresolvedItems) {
      const formatted = `Follow up: ${item}`
      if (!agenda.includes(formatted)) {
        agenda.push(formatted)
      }
    }
  }

  // Add overdue action items
  if (actionItems && actionItems.length > 0) {
    const unownedItems = actionItems.filter(a => !a.owner)
    for (const item of unownedItems) {
      agenda.push(`Assign owner: ${item.task}`)
    }
  }

  return agenda
}

module.exports = { buildNextAgenda }
